# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'poputka' do
    use_frameworks!
    
    # Pods for poputka
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'IQKeyboardManager'
    pod 'SidebarOverlay'
    pod 'Jelly'
    
    target 'poputkaTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'poputkaUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
